name: Code Quality Check

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

permissions:
  contents: write
  pull-requests: write

jobs:
  analyze-code:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment (if needed for AI feedback script)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.8'

      # Step 3: Pass the OpenAI API Key as an environment variable
      - name: Set Environment Variables
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          YOUR_GITHUB_TOKEN: ${{ secrets.YOUR_GITHUB_TOKEN}}
        run: echo "Environment variables OPENAI_API_KEY and YOUR_GITHUB_TOKEN are set."

      # Step 3: Run AI-powered feedback generator
      - name: AI Feedback
        run: |
          python scripts/ai_feedback.py

      # Step 4: Post results (optional if posting to PR or saving logs)
      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: analysis-results
          path: results/

  post-comments:
    needs: analyze-code
    runs-on: ubuntu-latest
    if: ${{ success() }}  # Runs only if 'analyze-code' completes successfully

    steps:
      # Step 1: Post comments to PR using GitHub API
      - name: Post Comments
        run: |
          python scripts/post_comments_to_pr.py
